### ISSUE TITLE
mermaid syntax in code blocks 

### ISSUE THREAD

**Issue by ttasovac** [ytisf/language-mermaid#2]
Hi.

I was wondering if you knew how to enable mermaid syntax also within code blocks in Markdown. It works for other languages (such as XML) but not for mermaid. 

Many thanks for making this syntax definition available in the first place.  

All best,
Toma

<img width="467" alt="2017-03-04 16 48 50" src="https://cloud.githubusercontent.com/assets/5304839/23580062/a1f3b710-00fa-11e7-9447-07cce7e526ac.png">

**Comment by elifry** [comment]
> Hi.
> 
> I was wondering if you knew how to enable mermaid syntax also within code blocks in Markdown. It works for other languages (such as XML) but not for mermaid.
> 
> Many thanks for making this syntax definition available in the first place.
> 
> All best,
> Toma
> 
> <img alt="2017-03-04 16 48 50" width="467" src="https://cloud.githubusercontent.com/assets/5304839/23580062/a1f3b710-00fa-11e7-9447-07cce7e526ac.png">

I have started working on adding support for snippets. I wanted this highlighting in markdown documents as well.

**Comment by elifry** [comment]
@ttasovac  After doing some digging, [language-markdown](https://github.com/burodepeper/language-markdown) has support for mermaid. If you install this package it will do language-mermaid syntax highlighting inside code blocks. However, this may change your other markdown highlighting. Does this resolve your issue or should we extend the grammar to use markdown?

@ytisf Do you have thoughts on this as well?

**Comment by ytisf** [comment]
As far as I can see this works and is enabled. 
Due to lack of input I'll go a head and close this. Thanks @elifry for the input and thanks @ttasovac for the comment. If you believe that this has not been fixed feel free to open another issue.
