### ISSUE TITLE
Syntax highlighting stops at accentuated character

### ISSUE THREAD

**Issue by ojob** [ytisf/language-mermaid#6]
Here's a graph I have, with an accent in it, saved at UFT-8:

    graph TD
        subgraph Gouvernance opérationnelle
            Gerant --dirige--> Salariés
        end

Here how it looks: the color stops at the "é" of "opérationnelle"
![image](https://user-images.githubusercontent.com/1648261/71154010-dda13a80-223a-11ea-8f90-d7521e14217a.png)

It's even worse if I fix the typo in `Gerant`, which normally deserve an accent as well, as the whole reste of the line is ignored:
![image](https://user-images.githubusercontent.com/1648261/71154044-f27dce00-223a-11ea-91b1-1eee27e6ba4a.png)

Installation informations :
* atom 1.41.0 x64
* language-mermaid 0.6.0

**Comment by ytisf** [comment]
Thanks Joel . 
Last commit should fix this issue. 
Unicode is always fun :)

**Comment by ojob** [comment]
Thanks for the quick feedback!

So, to get this working, I replaced the file `.atom\packages\language-mermaid\grammars\mermaid.cson` with the content as per commit 7c8734e, and here's the current result:

![image](https://user-images.githubusercontent.com/1648261/71240548-b5344180-2309-11ea-872d-d19d78351814.png)

→ resolution confirmed on my side :)
